version: '3.8'
name: sf-basic

services:
  sf-backend:
    container_name: sf_backend
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./../:/var/www/html
    env_file:
      - .env

  sf-nginx:
    image: nginx:1.21-alpine
    container_name: sf_nginx
    depends_on:
      - sf-backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
